version: "3"
services:
    web:
        container_name: "TVoidling"
        build:
            context: .
            dockerfile: Dockerfile 
        volumes: 
            - ./:/thevoidling
        ports:
            - '5000:5000'
        command: ["python","run.py"]
        links:
            - mysql:database
    mysql:
        container_name: "voidlingDatabase"
        image: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        
#ASDF