version: "3"
services:
    web:
        container_name: "TVoidling"
        build:
            context: .
            dockerfile: Dockerfile 
        volumes: ["./:/thevoidling"]
        ports:
            - '5000:5000'
        environment: 
            - FLASK_APP=main.py
            - FLASK_DEBUG = 1
        command: ["flask","run","--reload","--debugger","-h","0.0.0.0"]
