version: "3"
services:
    voidling:
        container_name: web
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '5000:5000'
        command: ["python","init_voidling.py"]
        env_file: &env_files
          - config/env
          - config/env.custom
        volumes:
            - ./:/thevoidling
    void_swarm:
        container_name: 'backend'
        image: thevoidling_voidling
        command: ["python", "init_void_swarm.py"]
        env_file: *env_files
        volumes:
            - ./:/thevoidling
